/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as HelpRouteImport } from './routes/help'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CaregiversRouteImport } from './routes/caregivers'
import { Route as CaregiverRouteImport } from './routes/caregiver'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as CaregiverIndexRouteImport } from './routes/caregiver.index'
import { Route as DashboardSupportRouteImport } from './routes/dashboard.support'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardServicesRouteImport } from './routes/dashboard.services'
import { Route as DashboardSavedRouteImport } from './routes/dashboard.saved'
import { Route as DashboardRecentRouteImport } from './routes/dashboard.recent'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardPatientsRouteImport } from './routes/dashboard.patients'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardMessagesRouteImport } from './routes/dashboard.messages'
import { Route as DashboardHistoryRouteImport } from './routes/dashboard.history'
import { Route as DashboardBookingsRouteImport } from './routes/dashboard.bookings'
import { Route as CaregiverSettingsRouteImport } from './routes/caregiver.settings'
import { Route as CaregiverServicesRouteImport } from './routes/caregiver.services'
import { Route as CaregiverReviewsRouteImport } from './routes/caregiver.reviews'
import { Route as CaregiverRequestsRouteImport } from './routes/caregiver.requests'
import { Route as CaregiverProfileRouteImport } from './routes/caregiver.profile'
import { Route as CaregiverPatientsRouteImport } from './routes/caregiver.patients'
import { Route as CaregiverNotificationsRouteImport } from './routes/caregiver.notifications'
import { Route as CaregiverMessagesRouteImport } from './routes/caregiver.messages'
import { Route as CaregiverInquiriesRouteImport } from './routes/caregiver.inquiries'
import { Route as CaregiverHistoryRouteImport } from './routes/caregiver.history'
import { Route as CaregiverEarningsRouteImport } from './routes/caregiver.earnings'
import { Route as CaregiverDocumentsRouteImport } from './routes/caregiver.documents'
import { Route as CaregiverCareNotesRouteImport } from './routes/caregiver.care-notes'
import { Route as CaregiverCallbacksRouteImport } from './routes/caregiver.callbacks'
import { Route as CaregiverAvailabilityRouteImport } from './routes/caregiver.availability'
import { Route as CaregiverActiveVisitsRouteImport } from './routes/caregiver.active-visits'
import { Route as AuthVerificationRejectedRouteImport } from './routes/auth.verification-rejected'
import { Route as AuthVerificationApprovedRouteImport } from './routes/auth.verification-approved'
import { Route as AuthRegistrationSuccessRouteImport } from './routes/auth.registration-success'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthPendingVerificationRouteImport } from './routes/auth.pending-verification'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AuthAccountReviewRouteImport } from './routes/auth.account-review'
import { Route as AuthAccessDeniedRouteImport } from './routes/auth.access-denied'
import { Route as DashboardMessagesIndexRouteImport } from './routes/dashboard.messages.index'
import { Route as DashboardCaregiversIndexRouteImport } from './routes/dashboard.caregivers.index'
import { Route as CaregiverMessagesIndexRouteImport } from './routes/caregiver.messages.index'
import { Route as AuthRegisterIndexRouteImport } from './routes/auth.register.index'
import { Route as DashboardMessagesIdRouteImport } from './routes/dashboard.messages.$id'
import { Route as DashboardCaregiversIdRouteImport } from './routes/dashboard.caregivers.$id'
import { Route as DashboardBookingsIdRouteImport } from './routes/dashboard.bookings.$id'
import { Route as CaregiverMessagesIdRouteImport } from './routes/caregiver.messages.$id'
import { Route as AuthRegisterFamilyRouteImport } from './routes/auth.register.family'
import { Route as AuthRegisterCaregiverRouteImport } from './routes/auth.register.caregiver'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CaregiversRoute = CaregiversRouteImport.update({
  id: '/caregivers',
  path: '/caregivers',
  getParentRoute: () => rootRouteImport,
} as any)
const CaregiverRoute = CaregiverRouteImport.update({
  id: '/caregiver',
  path: '/caregiver',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const CaregiverIndexRoute = CaregiverIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CaregiverRoute,
} as any)
const DashboardSupportRoute = DashboardSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardServicesRoute = DashboardServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSavedRoute = DashboardSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRecentRoute = DashboardRecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPatientsRoute = DashboardPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMessagesRoute = DashboardMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHistoryRoute = DashboardHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBookingsRoute = DashboardBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => DashboardRoute,
} as any)
const CaregiverSettingsRoute = CaregiverSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CaregiverRoute,
} as any)
const CaregiverServicesRoute = CaregiverServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => CaregiverRoute,
} as any)
const CaregiverReviewsRoute = CaregiverReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => CaregiverRoute,
} as any)
const CaregiverRequestsRoute = CaregiverRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => CaregiverRoute,
} as any)
const CaregiverProfileRoute = CaregiverProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CaregiverRoute,
} as any)
const CaregiverPatientsRoute = CaregiverPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => CaregiverRoute,
} as any)
const CaregiverNotificationsRoute = CaregiverNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => CaregiverRoute,
} as any)
const CaregiverMessagesRoute = CaregiverMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => CaregiverRoute,
} as any)
const CaregiverInquiriesRoute = CaregiverInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => CaregiverRoute,
} as any)
const CaregiverHistoryRoute = CaregiverHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => CaregiverRoute,
} as any)
const CaregiverEarningsRoute = CaregiverEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => CaregiverRoute,
} as any)
const CaregiverDocumentsRoute = CaregiverDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => CaregiverRoute,
} as any)
const CaregiverCareNotesRoute = CaregiverCareNotesRouteImport.update({
  id: '/care-notes',
  path: '/care-notes',
  getParentRoute: () => CaregiverRoute,
} as any)
const CaregiverCallbacksRoute = CaregiverCallbacksRouteImport.update({
  id: '/callbacks',
  path: '/callbacks',
  getParentRoute: () => CaregiverRoute,
} as any)
const CaregiverAvailabilityRoute = CaregiverAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => CaregiverRoute,
} as any)
const CaregiverActiveVisitsRoute = CaregiverActiveVisitsRouteImport.update({
  id: '/active-visits',
  path: '/active-visits',
  getParentRoute: () => CaregiverRoute,
} as any)
const AuthVerificationRejectedRoute =
  AuthVerificationRejectedRouteImport.update({
    id: '/auth/verification-rejected',
    path: '/auth/verification-rejected',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthVerificationApprovedRoute =
  AuthVerificationApprovedRouteImport.update({
    id: '/auth/verification-approved',
    path: '/auth/verification-approved',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthRegistrationSuccessRoute = AuthRegistrationSuccessRouteImport.update({
  id: '/auth/registration-success',
  path: '/auth/registration-success',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPendingVerificationRoute = AuthPendingVerificationRouteImport.update({
  id: '/auth/pending-verification',
  path: '/auth/pending-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAccountReviewRoute = AuthAccountReviewRouteImport.update({
  id: '/auth/account-review',
  path: '/auth/account-review',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAccessDeniedRoute = AuthAccessDeniedRouteImport.update({
  id: '/auth/access-denied',
  path: '/auth/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMessagesIndexRoute = DashboardMessagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardMessagesRoute,
} as any)
const DashboardCaregiversIndexRoute =
  DashboardCaregiversIndexRouteImport.update({
    id: '/caregivers/',
    path: '/caregivers/',
    getParentRoute: () => DashboardRoute,
  } as any)
const CaregiverMessagesIndexRoute = CaregiverMessagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CaregiverMessagesRoute,
} as any)
const AuthRegisterIndexRoute = AuthRegisterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRegisterRoute,
} as any)
const DashboardMessagesIdRoute = DashboardMessagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardMessagesRoute,
} as any)
const DashboardCaregiversIdRoute = DashboardCaregiversIdRouteImport.update({
  id: '/caregivers/$id',
  path: '/caregivers/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBookingsIdRoute = DashboardBookingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardBookingsRoute,
} as any)
const CaregiverMessagesIdRoute = CaregiverMessagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CaregiverMessagesRoute,
} as any)
const AuthRegisterFamilyRoute = AuthRegisterFamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => AuthRegisterRoute,
} as any)
const AuthRegisterCaregiverRoute = AuthRegisterCaregiverRouteImport.update({
  id: '/caregiver',
  path: '/caregiver',
  getParentRoute: () => AuthRegisterRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/caregiver': typeof CaregiverRouteWithChildren
  '/caregivers': typeof CaregiversRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/services': typeof ServicesRoute
  '/support': typeof SupportRoute
  '/auth/access-denied': typeof AuthAccessDeniedRoute
  '/auth/account-review': typeof AuthAccountReviewRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/pending-verification': typeof AuthPendingVerificationRoute
  '/auth/register': typeof AuthRegisterRouteWithChildren
  '/auth/registration-success': typeof AuthRegistrationSuccessRoute
  '/auth/verification-approved': typeof AuthVerificationApprovedRoute
  '/auth/verification-rejected': typeof AuthVerificationRejectedRoute
  '/caregiver/active-visits': typeof CaregiverActiveVisitsRoute
  '/caregiver/availability': typeof CaregiverAvailabilityRoute
  '/caregiver/callbacks': typeof CaregiverCallbacksRoute
  '/caregiver/care-notes': typeof CaregiverCareNotesRoute
  '/caregiver/documents': typeof CaregiverDocumentsRoute
  '/caregiver/earnings': typeof CaregiverEarningsRoute
  '/caregiver/history': typeof CaregiverHistoryRoute
  '/caregiver/inquiries': typeof CaregiverInquiriesRoute
  '/caregiver/messages': typeof CaregiverMessagesRouteWithChildren
  '/caregiver/notifications': typeof CaregiverNotificationsRoute
  '/caregiver/patients': typeof CaregiverPatientsRoute
  '/caregiver/profile': typeof CaregiverProfileRoute
  '/caregiver/requests': typeof CaregiverRequestsRoute
  '/caregiver/reviews': typeof CaregiverReviewsRoute
  '/caregiver/services': typeof CaregiverServicesRoute
  '/caregiver/settings': typeof CaregiverSettingsRoute
  '/dashboard/bookings': typeof DashboardBookingsRouteWithChildren
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/messages': typeof DashboardMessagesRouteWithChildren
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/patients': typeof DashboardPatientsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/recent': typeof DashboardRecentRoute
  '/dashboard/saved': typeof DashboardSavedRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/caregiver/': typeof CaregiverIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/auth/register/caregiver': typeof AuthRegisterCaregiverRoute
  '/auth/register/family': typeof AuthRegisterFamilyRoute
  '/caregiver/messages/$id': typeof CaregiverMessagesIdRoute
  '/dashboard/bookings/$id': typeof DashboardBookingsIdRoute
  '/dashboard/caregivers/$id': typeof DashboardCaregiversIdRoute
  '/dashboard/messages/$id': typeof DashboardMessagesIdRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
  '/caregiver/messages/': typeof CaregiverMessagesIndexRoute
  '/dashboard/caregivers/': typeof DashboardCaregiversIndexRoute
  '/dashboard/messages/': typeof DashboardMessagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/caregivers': typeof CaregiversRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/services': typeof ServicesRoute
  '/support': typeof SupportRoute
  '/auth/access-denied': typeof AuthAccessDeniedRoute
  '/auth/account-review': typeof AuthAccountReviewRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/pending-verification': typeof AuthPendingVerificationRoute
  '/auth/registration-success': typeof AuthRegistrationSuccessRoute
  '/auth/verification-approved': typeof AuthVerificationApprovedRoute
  '/auth/verification-rejected': typeof AuthVerificationRejectedRoute
  '/caregiver/active-visits': typeof CaregiverActiveVisitsRoute
  '/caregiver/availability': typeof CaregiverAvailabilityRoute
  '/caregiver/callbacks': typeof CaregiverCallbacksRoute
  '/caregiver/care-notes': typeof CaregiverCareNotesRoute
  '/caregiver/documents': typeof CaregiverDocumentsRoute
  '/caregiver/earnings': typeof CaregiverEarningsRoute
  '/caregiver/history': typeof CaregiverHistoryRoute
  '/caregiver/inquiries': typeof CaregiverInquiriesRoute
  '/caregiver/notifications': typeof CaregiverNotificationsRoute
  '/caregiver/patients': typeof CaregiverPatientsRoute
  '/caregiver/profile': typeof CaregiverProfileRoute
  '/caregiver/requests': typeof CaregiverRequestsRoute
  '/caregiver/reviews': typeof CaregiverReviewsRoute
  '/caregiver/services': typeof CaregiverServicesRoute
  '/caregiver/settings': typeof CaregiverSettingsRoute
  '/dashboard/bookings': typeof DashboardBookingsRouteWithChildren
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/patients': typeof DashboardPatientsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/recent': typeof DashboardRecentRoute
  '/dashboard/saved': typeof DashboardSavedRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/caregiver': typeof CaregiverIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/auth/register/caregiver': typeof AuthRegisterCaregiverRoute
  '/auth/register/family': typeof AuthRegisterFamilyRoute
  '/caregiver/messages/$id': typeof CaregiverMessagesIdRoute
  '/dashboard/bookings/$id': typeof DashboardBookingsIdRoute
  '/dashboard/caregivers/$id': typeof DashboardCaregiversIdRoute
  '/dashboard/messages/$id': typeof DashboardMessagesIdRoute
  '/auth/register': typeof AuthRegisterIndexRoute
  '/caregiver/messages': typeof CaregiverMessagesIndexRoute
  '/dashboard/caregivers': typeof DashboardCaregiversIndexRoute
  '/dashboard/messages': typeof DashboardMessagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/caregiver': typeof CaregiverRouteWithChildren
  '/caregivers': typeof CaregiversRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/services': typeof ServicesRoute
  '/support': typeof SupportRoute
  '/auth/access-denied': typeof AuthAccessDeniedRoute
  '/auth/account-review': typeof AuthAccountReviewRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/pending-verification': typeof AuthPendingVerificationRoute
  '/auth/register': typeof AuthRegisterRouteWithChildren
  '/auth/registration-success': typeof AuthRegistrationSuccessRoute
  '/auth/verification-approved': typeof AuthVerificationApprovedRoute
  '/auth/verification-rejected': typeof AuthVerificationRejectedRoute
  '/caregiver/active-visits': typeof CaregiverActiveVisitsRoute
  '/caregiver/availability': typeof CaregiverAvailabilityRoute
  '/caregiver/callbacks': typeof CaregiverCallbacksRoute
  '/caregiver/care-notes': typeof CaregiverCareNotesRoute
  '/caregiver/documents': typeof CaregiverDocumentsRoute
  '/caregiver/earnings': typeof CaregiverEarningsRoute
  '/caregiver/history': typeof CaregiverHistoryRoute
  '/caregiver/inquiries': typeof CaregiverInquiriesRoute
  '/caregiver/messages': typeof CaregiverMessagesRouteWithChildren
  '/caregiver/notifications': typeof CaregiverNotificationsRoute
  '/caregiver/patients': typeof CaregiverPatientsRoute
  '/caregiver/profile': typeof CaregiverProfileRoute
  '/caregiver/requests': typeof CaregiverRequestsRoute
  '/caregiver/reviews': typeof CaregiverReviewsRoute
  '/caregiver/services': typeof CaregiverServicesRoute
  '/caregiver/settings': typeof CaregiverSettingsRoute
  '/dashboard/bookings': typeof DashboardBookingsRouteWithChildren
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/messages': typeof DashboardMessagesRouteWithChildren
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/patients': typeof DashboardPatientsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/recent': typeof DashboardRecentRoute
  '/dashboard/saved': typeof DashboardSavedRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/caregiver/': typeof CaregiverIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/auth/register/caregiver': typeof AuthRegisterCaregiverRoute
  '/auth/register/family': typeof AuthRegisterFamilyRoute
  '/caregiver/messages/$id': typeof CaregiverMessagesIdRoute
  '/dashboard/bookings/$id': typeof DashboardBookingsIdRoute
  '/dashboard/caregivers/$id': typeof DashboardCaregiversIdRoute
  '/dashboard/messages/$id': typeof DashboardMessagesIdRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
  '/caregiver/messages/': typeof CaregiverMessagesIndexRoute
  '/dashboard/caregivers/': typeof DashboardCaregiversIndexRoute
  '/dashboard/messages/': typeof DashboardMessagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/caregiver'
    | '/caregivers'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/help'
    | '/how-it-works'
    | '/services'
    | '/support'
    | '/auth/access-denied'
    | '/auth/account-review'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/pending-verification'
    | '/auth/register'
    | '/auth/registration-success'
    | '/auth/verification-approved'
    | '/auth/verification-rejected'
    | '/caregiver/active-visits'
    | '/caregiver/availability'
    | '/caregiver/callbacks'
    | '/caregiver/care-notes'
    | '/caregiver/documents'
    | '/caregiver/earnings'
    | '/caregiver/history'
    | '/caregiver/inquiries'
    | '/caregiver/messages'
    | '/caregiver/notifications'
    | '/caregiver/patients'
    | '/caregiver/profile'
    | '/caregiver/requests'
    | '/caregiver/reviews'
    | '/caregiver/services'
    | '/caregiver/settings'
    | '/dashboard/bookings'
    | '/dashboard/history'
    | '/dashboard/messages'
    | '/dashboard/notifications'
    | '/dashboard/patients'
    | '/dashboard/profile'
    | '/dashboard/recent'
    | '/dashboard/saved'
    | '/dashboard/services'
    | '/dashboard/settings'
    | '/dashboard/support'
    | '/caregiver/'
    | '/dashboard/'
    | '/auth/register/caregiver'
    | '/auth/register/family'
    | '/caregiver/messages/$id'
    | '/dashboard/bookings/$id'
    | '/dashboard/caregivers/$id'
    | '/dashboard/messages/$id'
    | '/auth/register/'
    | '/caregiver/messages/'
    | '/dashboard/caregivers/'
    | '/dashboard/messages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/caregivers'
    | '/contact'
    | '/faq'
    | '/help'
    | '/how-it-works'
    | '/services'
    | '/support'
    | '/auth/access-denied'
    | '/auth/account-review'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/pending-verification'
    | '/auth/registration-success'
    | '/auth/verification-approved'
    | '/auth/verification-rejected'
    | '/caregiver/active-visits'
    | '/caregiver/availability'
    | '/caregiver/callbacks'
    | '/caregiver/care-notes'
    | '/caregiver/documents'
    | '/caregiver/earnings'
    | '/caregiver/history'
    | '/caregiver/inquiries'
    | '/caregiver/notifications'
    | '/caregiver/patients'
    | '/caregiver/profile'
    | '/caregiver/requests'
    | '/caregiver/reviews'
    | '/caregiver/services'
    | '/caregiver/settings'
    | '/dashboard/bookings'
    | '/dashboard/history'
    | '/dashboard/notifications'
    | '/dashboard/patients'
    | '/dashboard/profile'
    | '/dashboard/recent'
    | '/dashboard/saved'
    | '/dashboard/services'
    | '/dashboard/settings'
    | '/dashboard/support'
    | '/caregiver'
    | '/dashboard'
    | '/auth/register/caregiver'
    | '/auth/register/family'
    | '/caregiver/messages/$id'
    | '/dashboard/bookings/$id'
    | '/dashboard/caregivers/$id'
    | '/dashboard/messages/$id'
    | '/auth/register'
    | '/caregiver/messages'
    | '/dashboard/caregivers'
    | '/dashboard/messages'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/caregiver'
    | '/caregivers'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/help'
    | '/how-it-works'
    | '/services'
    | '/support'
    | '/auth/access-denied'
    | '/auth/account-review'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/pending-verification'
    | '/auth/register'
    | '/auth/registration-success'
    | '/auth/verification-approved'
    | '/auth/verification-rejected'
    | '/caregiver/active-visits'
    | '/caregiver/availability'
    | '/caregiver/callbacks'
    | '/caregiver/care-notes'
    | '/caregiver/documents'
    | '/caregiver/earnings'
    | '/caregiver/history'
    | '/caregiver/inquiries'
    | '/caregiver/messages'
    | '/caregiver/notifications'
    | '/caregiver/patients'
    | '/caregiver/profile'
    | '/caregiver/requests'
    | '/caregiver/reviews'
    | '/caregiver/services'
    | '/caregiver/settings'
    | '/dashboard/bookings'
    | '/dashboard/history'
    | '/dashboard/messages'
    | '/dashboard/notifications'
    | '/dashboard/patients'
    | '/dashboard/profile'
    | '/dashboard/recent'
    | '/dashboard/saved'
    | '/dashboard/services'
    | '/dashboard/settings'
    | '/dashboard/support'
    | '/caregiver/'
    | '/dashboard/'
    | '/auth/register/caregiver'
    | '/auth/register/family'
    | '/caregiver/messages/$id'
    | '/dashboard/bookings/$id'
    | '/dashboard/caregivers/$id'
    | '/dashboard/messages/$id'
    | '/auth/register/'
    | '/caregiver/messages/'
    | '/dashboard/caregivers/'
    | '/dashboard/messages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CaregiverRoute: typeof CaregiverRouteWithChildren
  CaregiversRoute: typeof CaregiversRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FaqRoute: typeof FaqRoute
  HelpRoute: typeof HelpRoute
  HowItWorksRoute: typeof HowItWorksRoute
  ServicesRoute: typeof ServicesRoute
  SupportRoute: typeof SupportRoute
  AuthAccessDeniedRoute: typeof AuthAccessDeniedRoute
  AuthAccountReviewRoute: typeof AuthAccountReviewRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthPendingVerificationRoute: typeof AuthPendingVerificationRoute
  AuthRegisterRoute: typeof AuthRegisterRouteWithChildren
  AuthRegistrationSuccessRoute: typeof AuthRegistrationSuccessRoute
  AuthVerificationApprovedRoute: typeof AuthVerificationApprovedRoute
  AuthVerificationRejectedRoute: typeof AuthVerificationRejectedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caregivers': {
      id: '/caregivers'
      path: '/caregivers'
      fullPath: '/caregivers'
      preLoaderRoute: typeof CaregiversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caregiver': {
      id: '/caregiver'
      path: '/caregiver'
      fullPath: '/caregiver'
      preLoaderRoute: typeof CaregiverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/caregiver/': {
      id: '/caregiver/'
      path: '/'
      fullPath: '/caregiver/'
      preLoaderRoute: typeof CaregiverIndexRouteImport
      parentRoute: typeof CaregiverRoute
    }
    '/dashboard/support': {
      id: '/dashboard/support'
      path: '/support'
      fullPath: '/dashboard/support'
      preLoaderRoute: typeof DashboardSupportRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/services': {
      id: '/dashboard/services'
      path: '/services'
      fullPath: '/dashboard/services'
      preLoaderRoute: typeof DashboardServicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/saved': {
      id: '/dashboard/saved'
      path: '/saved'
      fullPath: '/dashboard/saved'
      preLoaderRoute: typeof DashboardSavedRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/recent': {
      id: '/dashboard/recent'
      path: '/recent'
      fullPath: '/dashboard/recent'
      preLoaderRoute: typeof DashboardRecentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/patients': {
      id: '/dashboard/patients'
      path: '/patients'
      fullPath: '/dashboard/patients'
      preLoaderRoute: typeof DashboardPatientsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/messages': {
      id: '/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardMessagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/history': {
      id: '/dashboard/history'
      path: '/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof DashboardHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bookings': {
      id: '/dashboard/bookings'
      path: '/bookings'
      fullPath: '/dashboard/bookings'
      preLoaderRoute: typeof DashboardBookingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/caregiver/settings': {
      id: '/caregiver/settings'
      path: '/settings'
      fullPath: '/caregiver/settings'
      preLoaderRoute: typeof CaregiverSettingsRouteImport
      parentRoute: typeof CaregiverRoute
    }
    '/caregiver/services': {
      id: '/caregiver/services'
      path: '/services'
      fullPath: '/caregiver/services'
      preLoaderRoute: typeof CaregiverServicesRouteImport
      parentRoute: typeof CaregiverRoute
    }
    '/caregiver/reviews': {
      id: '/caregiver/reviews'
      path: '/reviews'
      fullPath: '/caregiver/reviews'
      preLoaderRoute: typeof CaregiverReviewsRouteImport
      parentRoute: typeof CaregiverRoute
    }
    '/caregiver/requests': {
      id: '/caregiver/requests'
      path: '/requests'
      fullPath: '/caregiver/requests'
      preLoaderRoute: typeof CaregiverRequestsRouteImport
      parentRoute: typeof CaregiverRoute
    }
    '/caregiver/profile': {
      id: '/caregiver/profile'
      path: '/profile'
      fullPath: '/caregiver/profile'
      preLoaderRoute: typeof CaregiverProfileRouteImport
      parentRoute: typeof CaregiverRoute
    }
    '/caregiver/patients': {
      id: '/caregiver/patients'
      path: '/patients'
      fullPath: '/caregiver/patients'
      preLoaderRoute: typeof CaregiverPatientsRouteImport
      parentRoute: typeof CaregiverRoute
    }
    '/caregiver/notifications': {
      id: '/caregiver/notifications'
      path: '/notifications'
      fullPath: '/caregiver/notifications'
      preLoaderRoute: typeof CaregiverNotificationsRouteImport
      parentRoute: typeof CaregiverRoute
    }
    '/caregiver/messages': {
      id: '/caregiver/messages'
      path: '/messages'
      fullPath: '/caregiver/messages'
      preLoaderRoute: typeof CaregiverMessagesRouteImport
      parentRoute: typeof CaregiverRoute
    }
    '/caregiver/inquiries': {
      id: '/caregiver/inquiries'
      path: '/inquiries'
      fullPath: '/caregiver/inquiries'
      preLoaderRoute: typeof CaregiverInquiriesRouteImport
      parentRoute: typeof CaregiverRoute
    }
    '/caregiver/history': {
      id: '/caregiver/history'
      path: '/history'
      fullPath: '/caregiver/history'
      preLoaderRoute: typeof CaregiverHistoryRouteImport
      parentRoute: typeof CaregiverRoute
    }
    '/caregiver/earnings': {
      id: '/caregiver/earnings'
      path: '/earnings'
      fullPath: '/caregiver/earnings'
      preLoaderRoute: typeof CaregiverEarningsRouteImport
      parentRoute: typeof CaregiverRoute
    }
    '/caregiver/documents': {
      id: '/caregiver/documents'
      path: '/documents'
      fullPath: '/caregiver/documents'
      preLoaderRoute: typeof CaregiverDocumentsRouteImport
      parentRoute: typeof CaregiverRoute
    }
    '/caregiver/care-notes': {
      id: '/caregiver/care-notes'
      path: '/care-notes'
      fullPath: '/caregiver/care-notes'
      preLoaderRoute: typeof CaregiverCareNotesRouteImport
      parentRoute: typeof CaregiverRoute
    }
    '/caregiver/callbacks': {
      id: '/caregiver/callbacks'
      path: '/callbacks'
      fullPath: '/caregiver/callbacks'
      preLoaderRoute: typeof CaregiverCallbacksRouteImport
      parentRoute: typeof CaregiverRoute
    }
    '/caregiver/availability': {
      id: '/caregiver/availability'
      path: '/availability'
      fullPath: '/caregiver/availability'
      preLoaderRoute: typeof CaregiverAvailabilityRouteImport
      parentRoute: typeof CaregiverRoute
    }
    '/caregiver/active-visits': {
      id: '/caregiver/active-visits'
      path: '/active-visits'
      fullPath: '/caregiver/active-visits'
      preLoaderRoute: typeof CaregiverActiveVisitsRouteImport
      parentRoute: typeof CaregiverRoute
    }
    '/auth/verification-rejected': {
      id: '/auth/verification-rejected'
      path: '/auth/verification-rejected'
      fullPath: '/auth/verification-rejected'
      preLoaderRoute: typeof AuthVerificationRejectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verification-approved': {
      id: '/auth/verification-approved'
      path: '/auth/verification-approved'
      fullPath: '/auth/verification-approved'
      preLoaderRoute: typeof AuthVerificationApprovedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/registration-success': {
      id: '/auth/registration-success'
      path: '/auth/registration-success'
      fullPath: '/auth/registration-success'
      preLoaderRoute: typeof AuthRegistrationSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/pending-verification': {
      id: '/auth/pending-verification'
      path: '/auth/pending-verification'
      fullPath: '/auth/pending-verification'
      preLoaderRoute: typeof AuthPendingVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/account-review': {
      id: '/auth/account-review'
      path: '/auth/account-review'
      fullPath: '/auth/account-review'
      preLoaderRoute: typeof AuthAccountReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/access-denied': {
      id: '/auth/access-denied'
      path: '/auth/access-denied'
      fullPath: '/auth/access-denied'
      preLoaderRoute: typeof AuthAccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/messages/': {
      id: '/dashboard/messages/'
      path: '/'
      fullPath: '/dashboard/messages/'
      preLoaderRoute: typeof DashboardMessagesIndexRouteImport
      parentRoute: typeof DashboardMessagesRoute
    }
    '/dashboard/caregivers/': {
      id: '/dashboard/caregivers/'
      path: '/caregivers'
      fullPath: '/dashboard/caregivers/'
      preLoaderRoute: typeof DashboardCaregiversIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/caregiver/messages/': {
      id: '/caregiver/messages/'
      path: '/'
      fullPath: '/caregiver/messages/'
      preLoaderRoute: typeof CaregiverMessagesIndexRouteImport
      parentRoute: typeof CaregiverMessagesRoute
    }
    '/auth/register/': {
      id: '/auth/register/'
      path: '/'
      fullPath: '/auth/register/'
      preLoaderRoute: typeof AuthRegisterIndexRouteImport
      parentRoute: typeof AuthRegisterRoute
    }
    '/dashboard/messages/$id': {
      id: '/dashboard/messages/$id'
      path: '/$id'
      fullPath: '/dashboard/messages/$id'
      preLoaderRoute: typeof DashboardMessagesIdRouteImport
      parentRoute: typeof DashboardMessagesRoute
    }
    '/dashboard/caregivers/$id': {
      id: '/dashboard/caregivers/$id'
      path: '/caregivers/$id'
      fullPath: '/dashboard/caregivers/$id'
      preLoaderRoute: typeof DashboardCaregiversIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bookings/$id': {
      id: '/dashboard/bookings/$id'
      path: '/$id'
      fullPath: '/dashboard/bookings/$id'
      preLoaderRoute: typeof DashboardBookingsIdRouteImport
      parentRoute: typeof DashboardBookingsRoute
    }
    '/caregiver/messages/$id': {
      id: '/caregiver/messages/$id'
      path: '/$id'
      fullPath: '/caregiver/messages/$id'
      preLoaderRoute: typeof CaregiverMessagesIdRouteImport
      parentRoute: typeof CaregiverMessagesRoute
    }
    '/auth/register/family': {
      id: '/auth/register/family'
      path: '/family'
      fullPath: '/auth/register/family'
      preLoaderRoute: typeof AuthRegisterFamilyRouteImport
      parentRoute: typeof AuthRegisterRoute
    }
    '/auth/register/caregiver': {
      id: '/auth/register/caregiver'
      path: '/caregiver'
      fullPath: '/auth/register/caregiver'
      preLoaderRoute: typeof AuthRegisterCaregiverRouteImport
      parentRoute: typeof AuthRegisterRoute
    }
  }
}

interface CaregiverMessagesRouteChildren {
  CaregiverMessagesIdRoute: typeof CaregiverMessagesIdRoute
  CaregiverMessagesIndexRoute: typeof CaregiverMessagesIndexRoute
}

const CaregiverMessagesRouteChildren: CaregiverMessagesRouteChildren = {
  CaregiverMessagesIdRoute: CaregiverMessagesIdRoute,
  CaregiverMessagesIndexRoute: CaregiverMessagesIndexRoute,
}

const CaregiverMessagesRouteWithChildren =
  CaregiverMessagesRoute._addFileChildren(CaregiverMessagesRouteChildren)

interface CaregiverRouteChildren {
  CaregiverActiveVisitsRoute: typeof CaregiverActiveVisitsRoute
  CaregiverAvailabilityRoute: typeof CaregiverAvailabilityRoute
  CaregiverCallbacksRoute: typeof CaregiverCallbacksRoute
  CaregiverCareNotesRoute: typeof CaregiverCareNotesRoute
  CaregiverDocumentsRoute: typeof CaregiverDocumentsRoute
  CaregiverEarningsRoute: typeof CaregiverEarningsRoute
  CaregiverHistoryRoute: typeof CaregiverHistoryRoute
  CaregiverInquiriesRoute: typeof CaregiverInquiriesRoute
  CaregiverMessagesRoute: typeof CaregiverMessagesRouteWithChildren
  CaregiverNotificationsRoute: typeof CaregiverNotificationsRoute
  CaregiverPatientsRoute: typeof CaregiverPatientsRoute
  CaregiverProfileRoute: typeof CaregiverProfileRoute
  CaregiverRequestsRoute: typeof CaregiverRequestsRoute
  CaregiverReviewsRoute: typeof CaregiverReviewsRoute
  CaregiverServicesRoute: typeof CaregiverServicesRoute
  CaregiverSettingsRoute: typeof CaregiverSettingsRoute
  CaregiverIndexRoute: typeof CaregiverIndexRoute
}

const CaregiverRouteChildren: CaregiverRouteChildren = {
  CaregiverActiveVisitsRoute: CaregiverActiveVisitsRoute,
  CaregiverAvailabilityRoute: CaregiverAvailabilityRoute,
  CaregiverCallbacksRoute: CaregiverCallbacksRoute,
  CaregiverCareNotesRoute: CaregiverCareNotesRoute,
  CaregiverDocumentsRoute: CaregiverDocumentsRoute,
  CaregiverEarningsRoute: CaregiverEarningsRoute,
  CaregiverHistoryRoute: CaregiverHistoryRoute,
  CaregiverInquiriesRoute: CaregiverInquiriesRoute,
  CaregiverMessagesRoute: CaregiverMessagesRouteWithChildren,
  CaregiverNotificationsRoute: CaregiverNotificationsRoute,
  CaregiverPatientsRoute: CaregiverPatientsRoute,
  CaregiverProfileRoute: CaregiverProfileRoute,
  CaregiverRequestsRoute: CaregiverRequestsRoute,
  CaregiverReviewsRoute: CaregiverReviewsRoute,
  CaregiverServicesRoute: CaregiverServicesRoute,
  CaregiverSettingsRoute: CaregiverSettingsRoute,
  CaregiverIndexRoute: CaregiverIndexRoute,
}

const CaregiverRouteWithChildren = CaregiverRoute._addFileChildren(
  CaregiverRouteChildren,
)

interface DashboardBookingsRouteChildren {
  DashboardBookingsIdRoute: typeof DashboardBookingsIdRoute
}

const DashboardBookingsRouteChildren: DashboardBookingsRouteChildren = {
  DashboardBookingsIdRoute: DashboardBookingsIdRoute,
}

const DashboardBookingsRouteWithChildren =
  DashboardBookingsRoute._addFileChildren(DashboardBookingsRouteChildren)

interface DashboardMessagesRouteChildren {
  DashboardMessagesIdRoute: typeof DashboardMessagesIdRoute
  DashboardMessagesIndexRoute: typeof DashboardMessagesIndexRoute
}

const DashboardMessagesRouteChildren: DashboardMessagesRouteChildren = {
  DashboardMessagesIdRoute: DashboardMessagesIdRoute,
  DashboardMessagesIndexRoute: DashboardMessagesIndexRoute,
}

const DashboardMessagesRouteWithChildren =
  DashboardMessagesRoute._addFileChildren(DashboardMessagesRouteChildren)

interface DashboardRouteChildren {
  DashboardBookingsRoute: typeof DashboardBookingsRouteWithChildren
  DashboardHistoryRoute: typeof DashboardHistoryRoute
  DashboardMessagesRoute: typeof DashboardMessagesRouteWithChildren
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardPatientsRoute: typeof DashboardPatientsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardRecentRoute: typeof DashboardRecentRoute
  DashboardSavedRoute: typeof DashboardSavedRoute
  DashboardServicesRoute: typeof DashboardServicesRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSupportRoute: typeof DashboardSupportRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCaregiversIdRoute: typeof DashboardCaregiversIdRoute
  DashboardCaregiversIndexRoute: typeof DashboardCaregiversIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBookingsRoute: DashboardBookingsRouteWithChildren,
  DashboardHistoryRoute: DashboardHistoryRoute,
  DashboardMessagesRoute: DashboardMessagesRouteWithChildren,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardPatientsRoute: DashboardPatientsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardRecentRoute: DashboardRecentRoute,
  DashboardSavedRoute: DashboardSavedRoute,
  DashboardServicesRoute: DashboardServicesRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSupportRoute: DashboardSupportRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCaregiversIdRoute: DashboardCaregiversIdRoute,
  DashboardCaregiversIndexRoute: DashboardCaregiversIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface AuthRegisterRouteChildren {
  AuthRegisterCaregiverRoute: typeof AuthRegisterCaregiverRoute
  AuthRegisterFamilyRoute: typeof AuthRegisterFamilyRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
}

const AuthRegisterRouteChildren: AuthRegisterRouteChildren = {
  AuthRegisterCaregiverRoute: AuthRegisterCaregiverRoute,
  AuthRegisterFamilyRoute: AuthRegisterFamilyRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
}

const AuthRegisterRouteWithChildren = AuthRegisterRoute._addFileChildren(
  AuthRegisterRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CaregiverRoute: CaregiverRouteWithChildren,
  CaregiversRoute: CaregiversRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FaqRoute: FaqRoute,
  HelpRoute: HelpRoute,
  HowItWorksRoute: HowItWorksRoute,
  ServicesRoute: ServicesRoute,
  SupportRoute: SupportRoute,
  AuthAccessDeniedRoute: AuthAccessDeniedRoute,
  AuthAccountReviewRoute: AuthAccountReviewRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthPendingVerificationRoute: AuthPendingVerificationRoute,
  AuthRegisterRoute: AuthRegisterRouteWithChildren,
  AuthRegistrationSuccessRoute: AuthRegistrationSuccessRoute,
  AuthVerificationApprovedRoute: AuthVerificationApprovedRoute,
  AuthVerificationRejectedRoute: AuthVerificationRejectedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
